[build]
builder = "nixpacks"
buildCommand = "cd server && npm install rimraf -g && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[variables]
NODE_ENV = "production"

# A configuração do MySQL será feita no Railway Dashboard
# Não é necessário definir aqui, pois o Railway irá fornecer 
# a variável DATABASE_URL automaticamente quando você adicionar
# o serviço MySQL 